import json
import os
notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# LLaMEA Pipeline Refactoring (Notebook Architecture)\n",
    "\n",
    "This notebook refactors the LLaMEA analysis pipeline into modular components using a Bottom-Up Recursive Translation strategy. It parses the log files, isolates the optimization classes, and translates the deepest nested blocks iteratively outwards."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "import json\n",
    "import shutil\n",
    "from datetime import datetime\n",
    "from pathlib import Path\n",
    "\n",
    "# --- Robust Path Navigation ---\n",
    "while Path.cwd().name != 'llamea-cameralens-workspace' and Path.cwd().parent != Path.cwd():\n",
    "    os.chdir('..')\n",
    "\n",
    "if Path.cwd().name != 'llamea-cameralens-workspace':\n",
    "    print(f\"⚠️ Warning: Could not find 'llamea-cameralens-workspace'. Current dir: {Path.cwd()}\")\n",
    "else:\n",
    "    print(f\"✅ Successfully navigated to workspace root: {Path.cwd()}\")\n",
    "\n",
    "# --- Configuration ---\n",
    "INPUT_DIR = Path(\"blade-framework/results/lens_vv4.1_150_50000_False2026-06-02_12-11-25/run-LLaMEA_v4_Improved-DoubleGauss_v4.1-0_20260602_121220/\")\n",
    "EXPERIMENT_NAME = \"LLaMEA_v4_Improved\"\n",
    "\n",
    "current_date = datetime.now().strftime(\"%d-%m-%Y\")\n",
    "OUTPUT_BASE = Path(f\"blade-framework/output-analysis/{EXPERIMENT_NAME}_{current_date}\")\n",
    "SUBFOLDERS = [\"stripped_data\", \"pseudocode_classes\", \"analysis\"]\n",
    "\n",
    "if OUTPUT_BASE.exists():\n",
    "    response = input(f\"Output directory '{OUTPUT_BASE}' already exists. Overwrite? (y/n): \")\n",
    "    if response.lower() == 'y':\n",
    "        shutil.rmtree(OUTPUT_BASE)\n",
    "        print(f\"Deleted existing directory: {OUTPUT_BASE}\")\n",
    "    else:\n",
    "        raise Exception(\"Execution halted by user to prevent overwrite.\")\n",
    "\n",
    "for folder in SUBFOLDERS:\n",
    "    (OUTPUT_BASE / folder).mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "print(f\"✅ Setup complete. Output base: {OUTPUT_BASE}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 2: Log Parsing\n",
    "def load_jsonl(filepath):\n",
    "    data = []\n",
    "    with open(filepath, 'r', encoding='utf-8') as f:\n",
    "        for line in f:\n",
    "            if line.strip():\n",
    "                data.append(json.loads(line))\n",
    "    return data\n",
    "\n",
    "log_path = INPUT_DIR / \"log.jsonl\"\n",
    "conv_log_path = INPUT_DIR / \"conversationlog.jsonl\"\n",
    "\n",
    "logs = load_jsonl(log_path) if log_path.exists() else []\n",
    "conv_logs = load_jsonl(conv_log_path) if conv_log_path.exists() else []\n",
    "\n",
    "merged_data = {}\n",
    "for entry in logs:\n",
    "    entry_id = entry.get(\"id\")\n",
    "    if entry_id:\n",
    "        merged_data[entry_id] = {\n",
    "            \"id\": entry_id,\n",
    "            \"generation\": entry.get(\"generation\", 0),\n",
    "            \"fitness\": entry.get(\"fitness\"),\n",
    "            \"parent\": entry.get(\"parent_ids\", []),\n",
    "            \"code\": entry.get(\"code\", \"\"),\n",
    "            \"feedback\": entry.get(\"feedback\", \"\"),\n",
    "            \"prompts\": []\n",
    "        }\n",
    "\n",
    "for conv in conv_logs:\n",
    "    conv_id = conv.get(\"id\") or conv.get(\"run_id\")\n",
    "    if conv_id and conv_id in merged_data:\n",
    "        merged_data[conv_id][\"prompts\"].append(conv)\n",
    "\n",
    "print(f\"Successfully mapped {len(merged_data)} optimization class entries.\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 3: Class Isolation & Stripping\n",
    "stripped_dir = OUTPUT_BASE / \"stripped_data\"\n",
    "variables_data = {}\n",
    "isolated_count = 0\n",
    "\n",
    "for entry_id, entry in merged_data.items():\n",
    "    code_content = entry.get(\"code\", \"\")\n",
    "    if code_content.strip():\n",
    "        py_filename = f\"optimisation_{entry_id}.py\"\n",
    "        file_path = stripped_dir / py_filename\n",
    "        with open(file_path, \"w\", encoding=\"utf-8\") as f:\n",
    "            f.write(code_content)\n",
    "        isolated_count += 1\n",
    "        \n",
    "        variables_data[entry_id] = {\n",
    "            \"id\": entry_id,\n",
    "            \"generation\": entry[\"generation\"],\n",
    "            \"fitness\": entry[\"fitness\"],\n",
    "            \"parent\": entry.get(\"parent\", []),\n",
    "            \"feedback\": entry[\"feedback\"],\n",
    "            \"local_path\": str(file_path.absolute())\n",
    "        }\n",
    "\n",
    "variables_path = stripped_dir / \"variables.json\"\n",
    "with open(variables_path, \"w\", encoding=\"utf-8\") as f:\n",
    "    json.dump(variables_data, f, indent=4)\n",
    "\n",
    "print(f\"📂 Isolated and saved {isolated_count} classes and variables.json to: {stripped_dir}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 4: Translation Engine (LLM Setup & Semantic Caching)\n",
    "import urllib.request\n",
    "import urllib.error\n",
    "import hashlib\n",
    "import time\n",
    "\n",
    "OLLAMA_URL = \"http://localhost:11434/api/chat\"\n",
    "DEFAULT_MODEL = \"qwen2.5-coder:14b\"\n",
    "FALLBACK_MODEL = \"mistral:latest\"\n",
    "\n",
    "def query_ollama(prompt, system_prompt=None, model=DEFAULT_MODEL, retries=3, delay=2):\n",
    "    messages = []\n",
    "    if system_prompt:\n",
    "        messages.append({\"role\": \"system\", \"content\": system_prompt})\n",
    "    messages.append({\"role\": \"user\", \"content\": prompt})\n",
    "    \n",
    "    data = {\n",
    "        \"model\": model,\n",
    "        \"messages\": messages,\n",
    "        \"stream\": False\n",
    "    }\n",
    "    \n",
    "    req = urllib.request.Request(\n",
    "        OLLAMA_URL,\n",
    "        data=json.dumps(data).encode(\"utf-8\"),\n",
    "        headers={\"Content-Type\": \"application/json\"}\n",
    "    )\n",
    "    \n",
    "    for attempt in range(1, retries + 1):\n",
    "        try:\n",
    "            with urllib.request.urlopen(req, timeout=240) as response:\n",
    "                res_body = response.read().decode(\"utf-8\")\n",
    "                res_json = json.loads(res_body)\n",
    "                return res_json[\"message\"][\"content\"]\n",
    "        except Exception as e:\n",
    "            print(f\"⚠️ [Ollama Attempt {attempt} Error]: {e}\")\n",
    "            if attempt == retries:\n",
    "                return query_ollama(prompt, system_prompt, model=FALLBACK_MODEL, retries=retries, delay=delay) if model == DEFAULT_MODEL else \"\"\n",
    "            time.sleep(delay * (2 ** (attempt - 1)))\n",
    "\n",
    "translation_cache = {}\n",
    "def get_chunk_hash(source):\n",
    "    return hashlib.sha256(source.encode(\"utf-8\")).hexdigest()\n",
    "\n",
    "def translate_chunk(chunk_text):\n",
    "    chunk_hash = get_chunk_hash(chunk_text)\n",
    "    if chunk_hash in translation_cache:\n",
    "        return translation_cache[chunk_hash], True\n",
    "        \n",
    "    system_prompt = (\n",
    "        \"You are the PseudocodeGeneratorAgent.\\n\"\n",
    "        \"Your task is to rewrite a Python block into highly readable, standardized pseudocode.\\n\\n\"\n",
    "        \"IMPORTANT: The Python code you receive may contain nested blocks that have ALREADY been translated into pseudocode. \"\n",
    "        \"These translated blocks will be wrapped in `// :::PSEUDOCODE:::` and `// :::END_PSEUDOCODE:::` comments. \"\n",
    "        \"You MUST seamlessly integrate these existing pseudocode blocks into your final translation of the surrounding Python code.\\n\\n\"\n",
    "        \"RULES:\\n\"\n",
    "        \"1. Math Notation: Translate optimization math into LaTeX.\\n\"\n",
    "        \"2. Variable Preservation: Preserve exact variable names.\\n\"\n",
    "        \"3. Structural Mapping: Replace conditional constructs with uppercase statements (IF/THEN/ELSE, FOR, WHILE).\\n\"\n",
    "        \"Return ONLY the pseudocode block. Do not add conversational text.\"\n",
    "    )\n",
    "    \n",
    "    prompt = f\"Translate the following code block into pseudocode:\\n\\n```python\\n{chunk_text}\\n```\"\n",
    "    translated_pseudocode = query_ollama(prompt, system_prompt)\n",
    "    translation_cache[chunk_hash] = translated_pseudocode\n",
    "    return translated_pseudocode, False\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 5: Recursive Bottom-Up Parser\n",
    "import textwrap\n",
    "\n",
    "def is_empty_or_comment(line):\n",
    "    s = line.strip()\n",
    "    return not s or s.startswith('#') or s.startswith('//')\n",
    "\n",
    "def get_indent(line):\n",
    "    s = line.expandtabs(4)\n",
    "    return len(s) - len(s.lstrip())\n",
    "\n",
    "def single_pass_translate(lines):\n",
    "    indents = []\n",
    "    for i, line in enumerate(lines):\n",
    "        if not is_empty_or_comment(line):\n",
    "            indents.append((i, get_indent(line)))\n",
    "            \n",
    "    blocks = []\n",
    "    for idx in range(len(indents) - 1):\n",
    "        i, ind = indents[idx]\n",
    "        next_i, next_ind = indents[idx+1]\n",
    "        \n",
    "        if next_ind > ind:\n",
    "            end_idx = idx + 1\n",
    "            has_nested = False\n",
    "            while end_idx < len(indents) and indents[end_idx][1] > ind:\n",
    "                if indents[end_idx][1] > next_ind:\n",
    "                    has_nested = True\n",
    "                end_idx += 1\n",
    "                \n",
    "            if not has_nested:\n",
    "                start_line = i\n",
    "                end_line = indents[end_idx-1][0]\n",
    "                blocks.append((start_line, end_line))\n",
    "                \n",
    "    if not blocks:\n",
    "        if not any(not is_empty_or_comment(l) for l in lines):\n",
    "            return lines, False\n",
    "            \n",
    "        text = \"\\n\".join(lines)\n",
    "        pseudocode, _ = translate_chunk(text)\n",
    "        pseudo_wrapped = [\"// :::PSEUDOCODE:::\"] + [f\"// {l}\" for l in pseudocode.split('\\n')] + [\"// :::END_PSEUDOCODE:::\"]\n",
    "        return pseudo_wrapped, True\n",
    "        \n",
    "    blocks.sort(key=lambda x: x[0], reverse=True)\n",
    "    new_lines = list(lines)\n",
    "    \n",
    "    for start, end in blocks:\n",
    "        block_lines = lines[start:end+1]\n",
    "        block_text = \"\\n\".join(block_lines)\n",
    "        \n",
    "        pseudocode, _ = translate_chunk(block_text)\n",
    "        base_indent = get_indent(lines[start])\n",
    "        prefix = \" \" * base_indent\n",
    "        \n",
    "        pseudo_wrapped = [f\"{prefix}// :::PSEUDOCODE:::\"]\n",
    "        for p_line in pseudocode.split('\\n'):\n",
    "            pseudo_wrapped.append(f\"{prefix}// {p_line}\")\n",
    "        pseudo_wrapped.append(f\"{prefix}// :::END_PSEUDOCODE:::\")\n",
    "        \n",
    "        new_lines[start:end+1] = pseudo_wrapped\n",
    "        \n",
    "    return new_lines, True\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 6: Execution & Saving Iterations\n",
    "pseudocode_dir = OUTPUT_BASE / \"pseudocode_classes\"\n",
    "\n",
    "for entry_id, entry in merged_data.items():\n",
    "    code_content = entry.get(\"code\", \"\")\n",
    "    if not code_content.strip(): continue\n",
    "    \n",
    "    class_dir = pseudocode_dir / f\"class_{entry_id}\"\n",
    "    class_dir.mkdir(parents=True, exist_ok=True)\n",
    "    \n",
    "    current_lines = code_content.split('\\n')\n",
    "    iteration = 1\n",
    "    \n",
    "    print(f\"🚀 Starting Recursive Translation for Optimizer {entry_id[:8]}...\")\n",
    "    while True:\n",
    "        new_lines, changed = single_pass_translate(current_lines)\n",
    "        \n",
    "        if not changed:\n",
    "            break\n",
    "            \n",
    "        iter_path = class_dir / f\"iteration_{iteration}.md\"\n",
    "        with open(iter_path, \"w\", encoding=\"utf-8\") as f:\n",
    "            f.write(\"\\n\".join(new_lines))\n",
    "            \n",
    "        print(f\"   ✅ Saved iteration {iteration} to {iter_path.name}\")\n",
    "        current_lines = new_lines\n",
    "        iteration += 1\n",
    "        \n",
    "print(f\"✨ All recursive translations complete. Data saved to {pseudocode_dir}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Cell 7: Clean Markdown Final Extraction\n",
    "def extract_clean_markdown(lines):\n",
    "    clean = []\n",
    "    for line in lines:\n",
    "        s = line.strip()\n",
    "        if s in [\"// :::PSEUDOCODE:::\", \"// :::END_PSEUDOCODE:::\"]:\n",
    "            continue\n",
    "        if line.lstrip().startswith(\"// \"):\n",
    "            indent = len(line) - len(line.lstrip())\n",
    "            clean.append(\" \" * indent + line.lstrip()[3:])\n",
    "        else:\n",
    "            clean.append(line)\n",
    "    return clean\n",
    "\n",
    "for entry_id, entry in merged_data.items():\n",
    "    class_dir = pseudocode_dir / f\"class_{entry_id}\"\n",
    "    if not class_dir.exists(): continue\n",
    "    \n",
    "    iter_files = list(class_dir.glob(\"iteration_*.md\"))\n",
    "    if not iter_files: continue\n",
    "    \n",
    "    latest_file = max(iter_files, key=lambda f: int(f.stem.split('_')[1]))\n",
    "    \n",
    "    with open(latest_file, \"r\", encoding=\"utf-8\") as f:\n",
    "        final_lines = f.read().split('\\n')\n",
    "        \n",
    "    clean_lines = extract_clean_markdown(final_lines)\n",
    "    \n",
    "    final_md_path = class_dir / \"final_pseudocode.md\"\n",
    "    with open(final_md_path, \"w\", encoding=\"utf-8\") as f:\n",
    "        f.write(\"\\n\".join(clean_lines))\n",
    "        \n",
    "print(\"✨ Clean final pseudocode extracted successfully.\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
with open("/Users/Yotam/.gemini/antigravity/worktrees/llamea-cameralens-workspace/init-llamea-analysis-pipeline/analysis_pipeline.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Notebook generated successfully!")